title: Blog Tech SchoolMouv
description: Blog technique de l'équipe de développement de SchoolMouv

url: https://Schoolmouv-team.github.io/blog
baseurl: "/blog"
paginate_path: "/page:num"
permalink: /:title

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: Team
    url: /team

social:
  github: Schoolmouv-team
  twitter: schoolmouv
  email: contact@schoolmouv.fr
# google_analytics: "UA-58263416-1"
